# <font color='orange'>Numpy Arrays</font>

In [1]:
import numpy as np

In [2]:
x =  np.array([1,2,3,4])
print(x)
print(np.arange(1,9)**4)
%timeit np.arange(1,9)**4 #Numpy arrays are faster than lists

[1 2 3 4]
[   1   16   81  256  625 1296 2401 4096]
1.87 μs ± 119 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
l = []
for i in range(0,4):
    ans = int(input("Enter the ans: "))
    l.append(ans)

print(l)
p = np.array(l)
print(p)
print(p.ndim)

[1, 2, 3, 4]
[1 2 3 4]
1


In [5]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]]) # Number of data should be same in both 
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [6]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [7]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [2]:
array = np.tile(np.arange(5), (5, 1)) #np.tile(A, reps)
print(array)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# <font color='orange'> Types of Numpy Arrays</font>

In [8]:
arr_zero = np.zeros((4))
print(arr_zero)
print("\n")
arr_zero1 = np.zeros((3,4))
print(arr_zero1)

[0. 0. 0. 0.]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
arr_one = np.ones((4))
print(arr_one)
print("\n")
arr_one1 = np.ones((3,4))
print(arr_one1)

[1. 1. 1. 1.]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
arr_emp = np.empty(4)
print(arr_emp) #In empty array, range of previous arrays comes in.

[1. 1. 1. 1.]


In [11]:
arr_range = np.arange(4)
print(arr_range)

[0 1 2 3]


In [12]:
arr_dia = np.eye(4)
print(arr_dia)
print("\n")
arr_dia1 = np.eye(3,5)
print(arr_dia1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [13]:
arr_line = np.linspace(0,100,num=5)
print(arr_line)

[  0.  25.  50.  75. 100.]


## <font color='orange'> Random</font>

Numpy also has lots of ways to create random number arrays:

**Rand:** Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

**Randn:** The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution with positive and negative values close to 0.  

**Ranf** Random float values inclusive of 0 and exclusive of 1 [0,1).

**Randint:** Return random integers from low (inclusive) to high (exclusive).  

**normal():** Draw random samples from a normal (Gaussian) distribution.


In [17]:
var = np.random.rand(4)
print(var)
print("\n")
var2 = np.random.rand(3,3)
print(var2)

[0.80638204 0.11316257 0.560944   0.41974636]


[[0.69003781 0.62591736 0.73238007]
 [0.35081282 0.41118861 0.35005282]
 [0.97544197 0.56312648 0.03065158]]


In [19]:
var3 = np.random.randn(4) #Close to zero with poitive + negative
print(var3)
print("\n")
var4 = np.random.randn(3,3)
print(var4)

[-0.0886702  -1.23064774 -1.90673551 -1.69766802]


[[ 0.40638343 -1.78853178 -0.42189194]
 [ 0.27882835  0.89165844  0.61026276]
 [-0.14829498  0.1273507  -0.30439012]]


In [21]:
var5 = np.random.ranf(4) 
print(var5)
print("\n")
var6 = np.random.ranf(3,3) # Only 1D array
print(var6)

[0.25999595 0.90901889 0.0929478  0.80135204]




TypeError: random_sample() takes at most 1 positional argument (2 given)

In [22]:
var7 = np.random.randint(5,20,4) #var7 = np.random.randint(min,max,total_value)
print(var7)
print("\n")
var8 = np.random.randint(0,3,3)
print(var8)

[18 17 10 18]


[0 1 2]


In [31]:
np.random.normal(loc=5, scale=4, size=(5, 4))   # loc - mean, scale-variance

array([[ 2.04490219,  6.1490287 , 12.94511852, -4.70419417],
       [-1.64695431,  3.01414257,  3.9554258 ,  5.20400875],
       [ 6.84151667,  0.88976775, -1.18047097,  7.38317102],
       [ 8.61254482,  3.83006197,  5.52645093,  0.88519134],
       [ 5.04633144, -3.06077632, 11.63216111,  6.57726592]])

# <font color='orange'> DataTypes</font>

In [25]:
dt1 = np.array([1,2,3,4,5])
print("Data Type is: ", dt1.dtype)
dt2 = np.array([1,2,3.0,4.0,5])
print("Data Type is: ", dt2.dtype)
dt3 = np.array([-1,2,3,-4,5])
print("Data Type is: ", dt3.dtype)
dt4 = np.array(["A","b","C"])
print("Data Type is: ", dt4.dtype)
dt5 = np.array(["A",10,"C"])
print("Data Type is: ", dt5.dtype)

Data Type is:  int64
Data Type is:  float64
Data Type is:  int64
Data Type is:  <U1
Data Type is:  <U21


In [29]:
dt6 = np.array([1,2,3,4,5], dtype = np.int8)
dt7 = dt6.astype(float)
dt8 = np.int_(dt7)
print("Data Type is: ", dt6.dtype)
print("Data Type is: ", dt7.dtype)
print("Data Type is: ", dt8.dtype)

Data Type is:  int8
Data Type is:  float64
Data Type is:  int64


# <font color='orange'> Arithmetic Operations</font>

In [30]:
arr1 = np.random.randint(low=0, high=20, size=10)
arr2 = np.random.randint(low=20, high=40, size=10)
print("Array1: ")
print(arr1)
print()
print("Array2: ")
print(arr2)

Array1: 
[16 16 16  3 10  4 19 17  1  2]

Array2: 
[37 23 35 25 27 26 28 34 32 36]


In [34]:
arr3 = arr1 + arr2
print(arr3)
arr4 = np.add(arr1,arr2)
print(arr4)

[53 39 51 28 37 30 47 51 33 38]
[53 39 51 28 37 30 47 51 33 38]


In [35]:
arr3 = arr1 - arr2
print(arr3)
arr4 = np.subtract(arr1,arr2)
print(arr4)

[-21  -7 -19 -22 -17 -22  -9 -17 -31 -34]
[-21  -7 -19 -22 -17 -22  -9 -17 -31 -34]


In [36]:
arr3 = arr1 * arr2
print(arr3)
arr4 = np.multiply(arr1,arr2)
print(arr4)

[592 368 560  75 270 104 532 578  32  72]
[592 368 560  75 270 104 532 578  32  72]


In [37]:
arr3 = arr1 / arr2
print(arr3)
arr4 = np.divide(arr1,arr2)
print(arr4)

[0.43243243 0.69565217 0.45714286 0.12       0.37037037 0.15384615
 0.67857143 0.5        0.03125    0.05555556]
[0.43243243 0.69565217 0.45714286 0.12       0.37037037 0.15384615
 0.67857143 0.5        0.03125    0.05555556]


In [38]:
arr3 = arr2 + 10
print(arr3)
arr4 = arr3 % 10
print(arr4)

[47 33 45 35 37 36 38 44 42 46]
[7 3 5 5 7 6 8 4 2 6]


In [43]:
ans = np.reciprocal(ar3)
print(ans)

[[[1 0 0 0]
  [1 0 0 0]
  [1 0 0 0]]]


In [40]:
arr5 = np.array([[1,2,3,4],[5,6,7,8]])
arr6 = np.array([[5,6,7,8],[1,2,3,4]])
print("Array5: ")
print(arr5)
print()
print("Array6: ")
print(arr6)

Array5: 
[[1 2 3 4]
 [5 6 7 8]]

Array6: 
[[5 6 7 8]
 [1 2 3 4]]


In [41]:
arr7 = arr5 + arr6
print(arr7)

[[ 6  8 10 12]
 [ 6  8 10 12]]


# <font color='orange'> Arithmetic Functions</font>

In [46]:
arr = np.array([5, 8, 9])
np.max(arr)

np.int64(9)

In [45]:
arr = np.array([[5, 8, 9],
                [2, 6, 15]])
np.max(arr, axis= 0)
np.max(arr, axis= 1)

array([ 9, 15])

In [49]:
arr = np.array([5, 8, 9])
np.min(arr)


np.int64(5)

In [48]:
arr = np.array([[5, 8, 9],
                [2, 6, 15]])
np.min(arr, axis= 0)
np.min(arr, axis= 1)

array([5, 2])

In [50]:
arr1 = np.array([2, 3, 4])
arr2 = np.array([1, 5, 2])
np.maximum(arr1, arr2)

array([2, 5, 4])

In [51]:
arr1 = np.array([2, 3, 4])
arr2 = np.array([1, 5, 2])
np.minimum(arr1, arr2)

array([1, 3, 2])

In [72]:
arr = np.array([4, 8, 9, 14, 2])
np.argmax(arr) # Returns the index of the maximum value along the axis

np.int64(3)

In [53]:

arr = np.array([[10, 14, 12],
                [13, 11, 15]])
np.argmax(arr, axis = 0)

array([1, 0, 1])

In [54]:
arr = np.array([4, 8, 9, 14, 2])
np.argmin(arr) # Returns the index of the minimum value along the axis

np.int64(4)

In [57]:
arr = np.array([[10, 14, 12],
               [13, 11, 15]])
np.argmin(arr, axis = 0)

array([0, 1, 0])

In [56]:
np.argmin(arr, axis = 1)

array([0, 1])

In [58]:
arr = np.array([[5, 7, 9],
                [4, 8, 12]])

np.sum(arr, axis = 0)

array([ 9, 15, 21])

In [59]:
np.sum(arr, axis = 1)

array([21, 24])

In [60]:
arr = np.array([[5, 7, 9],
                [4, 8, 12]])

np.mean(arr, axis = 0)

array([ 4.5,  7.5, 10.5])

In [61]:
np.mean(arr, axis = 1)

array([7., 8.])

In [62]:
arr = np.array([[1., 2.],
                [3., 4.]])

np.prod(arr, axis=1)

array([ 2., 12.])

In [63]:
arr = np.array([4, 36, 12, 49])
np.sqrt(arr)

array([2.        , 6.        , 3.46410162, 7.        ])

In [66]:
np.exp(arr)

array([5.45981500e+01, 4.31123155e+15, 1.62754791e+05, 1.90734657e+21])

In [67]:
np.sin(arr)

array([-0.7568025 , -0.99177885, -0.53657292, -0.95375265])

In [68]:
np.cos(arr)

array([-0.65364362, -0.12796369,  0.84385396,  0.30059254])

In [69]:
arr = np.array([2.3, 4.5, 6])
np.log(arr)

array([0.83290912, 1.5040774 , 1.79175947])

In [70]:
arr = np.array([2.5, 6.3, 4.9, 5.0, 6.8])
np.floor(arr)

array([2., 6., 4., 5., 6.])

In [71]:
arr = np.array([2.5, 6.3, 4.9, 5.0, 6.8])
np.ceil(arr)

array([3., 7., 5., 5., 7.])

In [36]:
# If both a and b are 1-D arrays, it is inner product of vectors.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.dot(a= arr1, b= arr2) # (4*1) + (2*5) + (3*6)

np.int64(32)

# <font color='orange'> Numpy shape and reshape</font>

In [5]:
sh = np.array([[2.5, 6.3],[4.9, 6.8], [1.2 , 4.8]])
print(sh.shape)

(3, 2)


In [12]:
sh1 = np.array([1,2,3,4] , ndmin = 4)
print(sh1)
print()
print(sh1.ndim)
print()
print(sh1.shape)
print()
print(sh1.reshape(2,2))
print()
print(sh1.reshape(-1))

[[[[1 2 3 4]]]]

4

(1, 1, 1, 4)

[[1 2]
 [3 4]]

[1 2 3 4]


# <font color='orange'> Indexing & Slicing </font>

# Same as Python

In [13]:
sh1 = np.array([1,2,3,4])
for i in np.nditer(sh1):
    print(i)

1
2
3
4


In [14]:
sh3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
for i in np.nditer(sh3):
    print(i)

1
2
3
4
1
2
3
4
1
2
3
4


In [15]:
sh3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
for i,d in np.ndenumerate(sh3):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
(0, 2, 0) 1
(0, 2, 1) 2
(0, 2, 2) 3
(0, 2, 3) 4


# <font color='orange'> Copy & View </font>

Copy: New array with new location and any changes in original doesn't reflect in copy one and vice versa.  
View: It just views the original array.

In [16]:
sh = np.array([[2.5, 6.3],[4.9, 6.8], [1.2 , 4.8]])
print(sh)
var = np.copy(sh)
print(var)

[[2.5 6.3]
 [4.9 6.8]
 [1.2 4.8]]
[[2.5 6.3]
 [4.9 6.8]
 [1.2 4.8]]


In [18]:
sh = np.array([[2.5, 6.3],[4.9, 6.8], [1.2 , 4.8]])
print(sh)
var = sh.view()
print(var)

[[2.5 6.3]
 [4.9 6.8]
 [1.2 4.8]]
[[2.5 6.3]
 [4.9 6.8]
 [1.2 4.8]]


# <font color='orange'> Join and Split </font>

In [21]:
arr1 = np.random.randint(low=0, high=20, size=10)
arr2 = np.random.randint(low=20, high=40, size=10)
print(arr1)
print()
print(arr2)
print()
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[16  6  9 19 12  6  7 10 17 14]

[36 20 24 38 22 39 22 26 30 22]

[16  6  9 19 12  6  7 10 17 14 36 20 24 38 22 39 22 26 30 22]


In [23]:
arr1 = np.array([[1,2],[2,4]])
arr2 = np.array([[1,2],[2,4]])
print(arr1)
print()
print(arr2)
print()
arr3 = np.concatenate((arr1,arr2), axis = 1)
print(arr3)
print()
arr4 = np.concatenate((arr1,arr2), axis = 0)
print(arr4)

[[1 2]
 [2 4]]

[[1 2]
 [2 4]]

[[1 2 1 2]
 [2 4 2 4]]

[[1 2]
 [2 4]
 [1 2]
 [2 4]]


In [33]:
ar_1 = np.array([1,2])
ar_2 = np.array([3,4])
print(ar_1)
print()
print(ar_2)
print()
ar_3 = np.stack((ar_1,ar_2), axis = 1)
print(ar_3)
print()
ar_4 = np.hstack((ar_1,ar_2)) #row
print(ar_4)
print()
ar_5 = np.vstack((ar_1,ar_2)) #column
print(ar_5)
print()
ar_6 = np.dstack((ar_1,ar_2)) #height
print(ar_6)

[1 2]

[3 4]

[[1 3]
 [2 4]]

[1 2 3 4]

[[1 2]
 [3 4]]

[[[1 3]
  [2 4]]]


In [35]:
ara = np.array([1,2,3,4,5,6])
print(ara)
print()
var = np.array_split(ara,3)
print(var)
print(type(var))

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
